### ISSUE TITLE
Mod to help with savegame testing?

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#111]
One of the big problems I have with savegame testing is that there will often be huge numbers of assets associated with the save, but most are not used on the map.

Would it be possible to create a separate mod that only associates used assets with the savegame, so when shared to workshop and someone else downloads it the "subscribe all" thing (in content manager > saves) only mentions used assets and enabled mods at the time the original author created the savegame?

The mods bit should be fairly easy as we already have some code for that (to check incompatible mods I think?) but the 'used assets' thing would likely need writing from scratch. It would also need to hook in to whatever bit of vanilla game creates the list of assets/mods when saving a game, to ensure that only assets on the map and enabled mods are in that list.

**Comment by krzychu124** [comment]
I know your pain 😄  I've already tried testing @DaEgi01 save but with my 16GB of RAM it is almost impossible. 
I've had to increase my pagefile to around 30Gigs to be able load game(I can't do other things because game eats every Kb of my RAM).
After loading I have almost 14GB in use... 
Tell me how can I open dnSpy if after loading modules it will eat almost 2GB, leaving a tiny bit for use (sometimes around 15MB... I can't even open Notepad++ with log without crash of my graphic card driver due to insufficient space).
I won't mention about lost time while loading game...

**Comment by aubergine10** [comment]
Yeah, I didn't ever manage to get that save to load and it took about 2 days to unsub all the gazillions of mods and assets and get things back to normal.

**Comment by ntoff** [comment]
Download the loadingscreen mod, "subscribe to all" in the save game manager, and in the loading screen mod, uncheck "load enabled assets" and only tick "load used assets"

**Comment by aubergine10** [comment]
That assets/mod config thing looks useful, I'll give that a try.

As for LSM's options, I've not managed to get those to work in that combination - it always seems to remove assets that the game is expecting because they're not placed on the map.

**Comment by 1Tomber** [comment]
Setting up a new Steam account and family share the game is also a nice idea:
https://www.reddit.com/r/CitiesSkylinesModding/comments/aw211s/increase_asset_editor_performance_with_lots_of/ehjn3os

**Comment by aubergine10** [comment]
I've compiled everything in this issue in to a small guide to help contributors who test savegames:

https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Tips-for-working-with-savegames

Thanks to everyone who contributed ideas!
