### ISSUE TITLE
Button to remove / disable all traffic lights

### ISSUE THREAD

**Issue by Sqoops** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#320]
Is it possible to implement a button that removes all traffic lights in your entire city? 

I tried implementing it myself but I can't figure out how to iterate the "ref NetNode node" from 0 to max and have it in a nested loop with 
`for (ushort nodeId = 0; nodeId < NetManager.MAX_NODE_COUNT; ++nodeId)`

**Comment by FireController1847** [comment]
I mean, it's certainly possible, but is it worth adding such a mundane feature to take up more screen space? I'm not sure what the use case for this would be...

**Comment by aubergine10** [comment]
@FireController1847 I assume this is due to the fact that Toggle Traffic Lights mod is incompatible with TM:PE (it breaks some of our traffic light stuff for an as-yet unknown reason).

@Sqoops Is it removal of traffic lights that's the most important thing, or an option to disable new traffic lights being automatically added at junctions that would normally get them?

**Comment by Sqoops** [comment]
@FireController1847 I've implemented a button already like this [picture](https://imgur.com/a/Ny38GH3?) which doesn't seem to waste that much space.

@aubergine10 an option to disable new traffic lights being automatically added to new junctions would be good enough for me.

**Comment by webfischi** [comment]
I had TTL still installed with game version 1.11 and TM:PE 10.18, if you just use the checkbox "Disable Traffic Lights" it works fine. So there shouldn't be an issue adding the feature, it could even use the original code from the mod, because it doesn't touch existing traffic lights.

**Comment by aubergine10** [comment]
Implemented in v11.0-alpha9
