### ISSUE TITLE
"Fatal crash": Looking for solutions

### ISSUE THREAD

**Issue by jomun** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#356]
### Reproduction Steps
Add more steps as nessecary.
1. Make sure that all mods listed below are activated
2. Load game
3. Crashes around 5-6 mins in when the section "Sunny Properties"

### Mod List

73 active mods

* TM:PE xx.xx
* 81 tiles
* Achieve it!
* Advanced Stop Selection
* Advanced Vehicle Options 1.8.5
* Airport roads 1.3.7
* Ambient Sounds Tuner
* Cargo hold fix
* Cinematic camera
* Control building level up
* CSL Show more limits
* Decal prop fix
* Dynamic Resolution
* Extra Landscaping tools
* Extra train station tracks
* findit! 1.55.4
* fine road anarchy 1.3.5
* fine road tool 1.3.7
* forest brush
* garbage bin controller
* improved public transport 2
* Japanese localization RD (for road names)
* kaguki jp ambiance pack
* konnos Japanese sounds
* less steam
* loading screen mod
* more network stuff
* move it 2.4.1
* network extensions 2
* network skins 2
* network tiling
* no abandonment
* no death care
* no fires
* no radioactive desert and more!
* No seagulls
* one way train tracks
* plop the growables
* ploppable asphalt
* ploppable rico
* prefab hook
* procedural objects 1.5.5
* prop and tree anarchy
* prop it up! 1.4.4
* prop line tool
* prop precision 1.0.1
* prop snapping
* prop unlimiter
* quay anarchy
* railway replacer
* realistic walking speed
* remove dirt (tree related)
* remove need for pipes
* removes street arrows
* service vehicle selector 2
* shadow strength adjuster
* single train track ai
* spawn points fix
* surface painter
* theme decals
* tram station track
* transparency LOD fix + Cloud Assets enabler
* transport line rendering fix
* tree movement control
* tree snapping 
* ultimate eye candy
* ultimate level of detail
* unlimited money
* unlimited trees mod
* unlimited outside connections
* unlock all
* WG citizen life cycle rebalance

### Output Log

[error.log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3265739/error.log.txt)

### Additional Info

Though my memory spikes to 96%... my ram capacity has never been an issue in the past. My computer has 16 gigs of ram and a GTX 960 graphics card.

**Comment by aubergine10** [comment]
It looks like you've shared `error.log`; we need the `output_log.txt` instead

See: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Share-your-Cities-Skylines-log-file

**Comment by jomun** [comment]
Initialize engine version: 5.6.7f1 (e80cc3114ac1)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: NVIDIA GeForce GTX 960 (ID=0x1401)
    Vendor:   NVIDIA
    VRAM:     2016 MB
    Driver:   23.21.13.8859
Begin MonoManager ReloadAssembly
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\Assembly-CSharp-firstpass.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\Assembly-CSharp-firstpass.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\Assembly-CSharp.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\Assembly-CSharp.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.UI.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.UI.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.Networking.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\UnityEngine.Networking.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ColossalManaged.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ColossalManaged.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ICSharpCode.SharpZipLib.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ICSharpCode.SharpZipLib.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ICities.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\ICities.dll into Unity Child Domain
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\PopsApiWrapper.dll (this message is harmless)
Loading E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\PopsApiWrapper.dll into Unity Child Domain
- Completed reload, in  0.034 seconds
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\System.Core.dll (this message is harmless)
Platform assembly: E:\Games\steamapps\common\Cities_Skylines\Cities_Data\Managed\System.dll (this message is harmless)
<RI> Initializing input.

<RI> Input initialized.

desktop: 1920x1080 60Hz; virtual: 3200x1080 at 0,0
<RI> Initialized touch support.

UnloadTime: 0.880051 ms
Game mode
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.261557 ms
Machine ID: 15c298cb78917409bb9964cc446525b360aa1f30
Model: MS-7922 (MSI)
OS: Windows 10  (10.0.0) 64bit
Language: English
CPU: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (4 core(s))
System Memory: 16332
Gfx Device: NVIDIA GeForce GTX 960
Gfx Version: Direct3D 11.0 [level 11.1]
Gfx Memory: 2016
Gfx Shader Model: 50
Game Version: 1.12.1-f2-steam-win

 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

API: Steam Type: Steam
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting initial resolution to 1920 1080 True  [Core]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Setting vsync to 2  [Core]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Raw Command Line: E:\Games\steamapps\common\Cities_Skylines\Cities.exe
Arguments: E:\Games\steamapps\common\Cities_Skylines\Cities.exe
  [CommandLine - Internal]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by aubergine10** [comment]
Can you just drag the `output_log.txt` file on to the comment text box below - it will upload it as a file, rather than paste it.

**Comment by jomun** [comment]
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3265749/output_log.txt)

**Comment by jomun** [comment]
by chance, is there any way that I can fix it?

**Comment by krzychu124** [comment]
I would try to increase page file (from your error log - only 47GB ~150MB free) because it looks like it's too low for your set of subscribed assets. Extend it up to e.g. 55-60GB and try again.

**Comment by jomun** [comment]
I will try it out

**Comment by aubergine10** [comment]
Ok, so it's crashing during the loading process (specifically near the end while mods are initialising).

It's not a TM:PE error, but let's see if we can get this fixed anyway...

The following assets are causing errors in the log (unlikely to cause the crash, but might as well unsubscribe them):

* [Culvert](https://steamcommunity.com/sharedfiles/filedetails/?id=891354992)
* [HSBC Tower](https://steamcommunity.com/sharedfiles/filedetails/?id=421304643)
* [Hiraya_00](https://steamcommunity.com/sharedfiles/filedetails/?id=418205510)

These are breaking due to missing required items (I suggest unsubscribe them for now, until the crash bug is resolved):

* [Glass Cube Metro Station](https://steamcommunity.com/sharedfiles/filedetails/?id=1534689224) - requires Metro Overhaul Mod
* [Beijing Inner City Wall Accessories](https://steamcommunity.com/sharedfiles/filedetails/?id=1248070473) - requires invisible paths and draggable wall

There are issues with the following mods:

* [Control Building Level Up](https://steamcommunity.com/sharedfiles/filedetails/?id=410535198) - this mod is obsolete and game breaking; is the "Historic building" option (on building info panels) in the base game instead
* Prop Unlimiter (asset id: 886603352) - no longer in workshop, was game breaking; unsubscribe
* [Remove Dirt](https://steamcommunity.com/sharedfiles/filedetails/?id=548149310) - obsolete; use [Hide It](https://steamcommunity.com/sharedfiles/filedetails/?id=1591417160) instead
* [Advanced Toolbar](https://steamcommunity.com/sharedfiles/filedetails/?id=563229150) - incompatible with some of the other mods you use, use [Resize It](https://steamcommunity.com/sharedfiles/filedetails/?id=1577882296) instead

I also noticed you have two versions of **Network Skins** installed. I would _suggest using the older one_ for now, as **Network Skins 2** has some crash bugs (its still in beta). Note also that Network Skins 2 won't be compatible with the Road Options (Color Changer++) mod.

**Comment by jomun** [comment]
So I tried it again and I got another crash. I did all of the changes except 1 which is related to (asset id: 886603352) I looked through my game and I couldnt find it. Is there by chance a way to locate and manually remove the file?
[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3267800/output_log.txt)

**Comment by aubergine10** [comment]
The 886603352 mod will appear as something like "Prop Unlimiter" in Main Menu > Content Manager > Mods.

On disk it is likely living in: `E:\Games\steamapps\workshop\content\255710\886603352` folder.

Try removing that first (ideally via Content Manager > Mods screen) and see if that fixes it.

If that doesn't fix it:

* Try disabling any graphics enhancement mods (things like Ultimate Eye Candy, Relight, Softer Shadows, etc).
* Make sure your graphics card drivers are up to date (download latest versions direct from Nvidia website)
* Try forcing DirectX 9 using the `-force-d3d9` [launch parameter](https://steamcommunity.com/sharedfiles/filedetails/?id=466981085)

If it's still not working after all that, then it's most likely that you're just running out of RAM due to all those workshop assets. Unsubscribe any you don't use; you can see your subscribed assets in Steam Workshop: Go to the Workshop tab, on the right where it says "Your files" choose "Subscribed Items" from the drop-down list, then you see everything you've subscribed in there and can unsubscribe any you don't use.

Note: Don't unsubscribe any roads or tracks (or any mods that add roads/tracks) as that will also break game loading (see [How to remove workshop networks](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/How-to-remove-workshop-networks) for correct procedure; but you need to be able to load your save game to do it).

**Comment by jomun** [comment]
So ive updated my drivers to the latest version and i have removed the prop unlimiiter mod.
I haven't removed my graphics mods just yet. But id id get another crash.

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3267959/output_log.txt)

1 of the crashes crashed my entire system and I unfortunately didnt get an output log for that one. 
2 other crashes before this one didnt give me out put logs.

**Comment by aubergine10** [comment]
Ok, try adding the `--noWorkshop` launch option; while present, it will disable all your assets and mods essentially returning game to vanilla state. If it still crashes, for example when starting a new game on new map, that would rule out all the workshop stuff and indicate that the game itself is causing the problem in which case you'll need to [submit a bug report to Paradox](https://forum.paradoxplaza.com/forum/index.php?applicationform/cities-skylines-steam-bug-report.6/form) ([more details here](https://steamcommunity.com/app/255710/discussions/0/3264459260621898028/)).

I noticed you've moved the game to drive E: - when did you make that change? Did these crashes start after doing that? If so, it's likely you used wrong procedure to move game to that drive, see: [How to move the game to a different disk drive](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/How-to-move-the-game-to-a-different-disk-drive).

**Comment by jomun** [comment]
So once I put in the start process for --noworkshop the game opened and I was able to load into a new map.

When I started to run the game again with the no workshop setting off it crashed.

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3268947/output_log.txt)


About the E: drive The game has been on my E: drive ever since I originally downloaded it. So I dont think that is the factor behind my computer's stalling crashes.

**Comment by aubergine10** [comment]
That most recent log shows you are running out  of memory:

```
DynamicHeapAllocator allocation probe 1 failed - Could not get memory for large allocation 4194320.
DynamicHeapAllocator allocation probe 1 failed - Could not get memory for large allocation 4194320.
DynamicHeapAllocator allocation probe 2 failed - Could not get memory for large allocation 4194320.
DynamicHeapAllocator allocation probe 3 failed - Could not get memory for large allocation 4194320.
DynamicHeapAllocator allocation probe 4 failed - Could not get memory for large allocation 4194320.
DynamicHeapAllocator out of memory - Could not get memory for large allocation 4194320!
Crash!!!
```

You need to unsubscribe workshop assets / [skip vanilla assets](https://steamcommunity.com/workshop/filedetails/discussion/667342976/1741105805762370419/) / buy more RAM, or a combination of those things. Otherwise the game will just keep crashing when it runs out of memory.

**Comment by jomun** [comment]
Hmm... I see. Well I have been considering in upgrading my computer as of recent so I suppose that the time to upgrade has come.  Thanks for the help.

**Comment by krzychu124** [comment]
How big is your page file now, I'm just curious? 

As far as I know game will try to use that virtual memory when system is low on RAM, always... 
Games and other programs are designed to use page file when running low on RAM available or loaded objects are not frequently used(like game assets).

I've never had a problem loading savegame. I have 16GB and I could load savegame with 2k-2.5k assets enabled( >60GB in-memory) without problems and even with running debugger which took around 2-3GB RAM.
 
If your page file is too small, the game will crash to desktop without any notification and that's clear sign that your page file is too small to load game with current amount of game assets.

**Comment by jomun** [comment]
Whats a good size recommendation for page file right now mine is set to
system preference

**Comment by krzychu124** [comment]
Depends on how many workshop assets you have subscribed. Sometimes <20GB would be enough but I've had a chance to load savegames where having 60GB wasn't enough to load game without crash. If you use 'system preference' please check if you have free disk space available because system will grab that free space for page file to increase it's size if necessary.

**Comment by jomun** [comment]
I checked the limits of my page file turnes out that my C: drive was
running out of memory when loading  the game. So I added a new page file to
my E: drive which has more space open and I got the game to run normally
again so I can say with relief that the problem has been solved.
