### ISSUE TITLE
NuGet for ClrHeapAllocationAnalyzer

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#464]
Would be nice if we could auto-install the `ClrHeapAllocationAnalyzer` via NuGet:

https://www.nuget.org/packages/ClrHeapAllocationAnalyzer/

Info: https://github.com/microsoft/RoslynClrHeapAllocationAnalyzer

**Comment by dymanoid** [comment]
Are you sure everyone needs this?

**Comment by aubergine10** [comment]
I'm not sure, it was @krzychu124 who suggested to use it and I just assumed it might be useful to include it by default in similar way to #463 

@krzychu124  What do you think?

**Comment by dymanoid** [comment]
When you activate that Analyzer, you'll get thousands of hints and warnings. Are you sure this is somewhat useful?

The Analyzer was meant to be used for high-perf assemblies only, where the code must avoid or minimize the memory pressure. Like server components of a big data processing system or near-real-time simulation software.

While it indeed can be useful for Unity based games too (minimizing the memory pressure in the game simulation loop), I personally don't see any benefit in using the Analyzer "all the way" for every C# project.

**Comment by krzychu124** [comment]
Yes..., I've just tested that and I don't think that would be useful for everyone. 
Personally I think that IDE plugin is better alternative for that because you can turn it on/off on demand.
Like @dymanoid we don't need to optimize every file and for performance critical parts of mod I can turn on plugin, check suggestions and make some changes in those places.

**Comment by aubergine10** [comment]
Fair point.
