### ISSUE TITLE
Conflict with Klyte45's Trees Respiration Mod

### ISSUE THREAD

**Issue by TroublesomeCorvid** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#484]
### Description
Whenever TP:ME and Trees Respiration are active at the same time I get an error from TP:ME about a mod conflict.

I've already left a message to Klyte45 on the workshop page of his mod, but this is my first time doing this - I don't know if he's going to get in touch with you or not.

### Reproduction Steps
Add more steps as necessary.
1. Have TP:ME and Trees Respiration active
2. Start a new city

### Mod List
Please list the mods enabled when you noticed the bug.

I started a new city in vanilla mode save for Trees Respiration and TP:ME being the only active mods.  I still got an error message, so I'm pretty sure that there aren't any other mods messing with this.  To make doubly sure, I replaced what mods I could with the ones in your reccomended mods list.  Still no love.

### Output Log

[output_log.txt](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/3495214/output_log.txt)

**Comment by krzychu124** [comment]
Hi, the problem is that both Stable and Labs versions of TM:PE are using different method redirection. Trees Respiration mod is connecting it's methods to original call chain but our redirector overwrite that original method so it sometimes works, sometimes not, depends on which mod is loaded first(random).

Our latest alpha build is rewritten to use the same approach for redirecting methods as used in Trees Respiration and many other mods. 
Both mods should work without issues on alpha build.

If you want to became a tester, here is the link.
[TM:PE v11-alpha6](https://steamcommunity.com/sharedfiles/filedetails/?l=english&id=1806963141) 

Please read and follow instructions in description.

**Comment by TroublesomeCorvid** [comment]
Thanks much.  I'll give it a shot later on in the next day or two here.

**Comment by nonchip** [comment]
i've got the labs version, and it still warns me not to use the respiration mod. but there doesn't seem to be an issue running both at once. is that just because the 2 versions share the same list of incompatible mods?

**Comment by aubergine10** [comment]
They are now compatible thanks to update by @Klyte45, I'm just about to update the compatibility list to stop the warning.

**Comment by nonchip** [comment]
thanks just wanted to double check with you :)
