### ISSUE TITLE
Docs: Some questions re: Reckless drivers

### ISSUE THREAD

**Issue by aubergine10** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#59]
Are there any restrictions on which vehicles can become reckless drivers (eg. can post vans, busses, ships, planes, etc., be reckless)?

As per discussions in #11, am I correct in saying that reckless drivers will no longer enter blocked junctions (and this also applies to on-call emergency vehicles)?

As per https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/41#issuecomment-461673615 , is it true that reckless drivers will obey custom lane connectors?

How do reckless drivers behave at timed traffic lights?

Do they obey the recently introduced **turn on red** feature (specifically when a junction does not allow it)?

Do they obey junctions that disallow u-turns?

**Comment by krzychu124** [comment]
>Are there any restrictions on which vehicles can become reckless drivers (eg. can post vans, busses, ships, planes, etc., be reckless)?

I don't think so. I will check that.
>How do reckless drivers behave at timed traffic lights?

They are ignoring traffic lights state (vanilla and timed too)
>As per discussions in #11, am I correct in saying that reckless drivers will no longer enter blocked junctions (and this also applies to on-call emergency vehicles)?

They should no longer enter blocked junctions.
Unfortunately it seems that under some unknown conditions for me at one junctions with level crossings (one way bus lane) regular vehicles ignored closed level crossing (with disabled enter on blocked junction option) I've had to delete this node and replace with new to fix this behavior. I have no idea how reproduce that now...
>As per [#41 (comment)](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/41#issuecomment-461673615) , is it true that reckless drivers will obey custom lane connectors?

I didn't check that yet but it is on my *very long TODO* list 😃 
>Do they obey the recently introduced **turn on red** feature (specifically when a junction does not allow it)?

Doesn't matter because that's still junction with traffic lights, so they ignore it

>Do they obey junctions that disallow u-turns?

I have never seen Ambulance doing U-turn 😄

**Comment by aubergine10** [comment]
Docs updated: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Reckless-Drivers
