### ISSUE TITLE
Possible load problem with Mac

### ISSUE THREAD

**Issue by pallamf** [krzychu124/Cities-Skylines-Traffic-Manager-President-Edition#669]
### Describe the problem
Unfortunately, I was unable to reproduce the problem after occurring several times yesterday.  See the description for the original problem, then see the update below.

I'm using Steam on a Mac, and switched to V11 yesterday. I removed 10.2, installed 11. When I load games, the bottom menu strip loads about 5 seconds later. The key commands work, I can zoom around, click on things, etc. The only thing that doesn't work is when I take the game off pause, the time and traffic doesn't do anything. It seems like it hangs, but again, I can still scroll around, click on other menus, etc. It just doesn't "run". Then, when I try to quit, it'll hang.
I removed v11, reinstalled 10.2, and it all worked normally again.
I do have a pause on start mod loaded.

Update:
I tried to reproduce this morning, and cannot reproduce the above problem.
The only thing I can remember that I did differently is, I still had 10.2 installed, and received a conflict warning to disable 10.2.  I allowed it to automatically disable 10.2.  Then later, it said I had to unsubscribe from 10.2, which I let it do.  I then went back to 10.2.
This morning, I connected up 11, and it seems to be working today.  So perhaps the auto conflict detection didn't disable 10.2 correctly.  I added the log file and mod list below.

On an unrelated note, I do not have the problem that JD DFW report in Steam.  I can add and place roads. 

### Steps to reproduce

1. 
2. 
3. 

### Log files

Player log  https://ufile.io/yqfp835k
Mod config   https://ufile.io/yxz2ae5y

**Comment by aubergine10** [comment]
Looks like some errors from other mods....

```diff
- Citizen not found!
   at System.Environment.get_StackTrace()
   at Building.RemoveTargetCitizen(UInt16 instanceID, CitizenInstance ByRef data)
   at TouristAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetIndex, Boolean targetIsNode)
   at CitizenAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetBuilding)
   at HumanAI.ArriveAtDestination_Patch1(System.Object , UInt16 , CitizenInstance ByRef , Boolean )
   at TouristAI.ArriveAtDestination(UInt16 instanceID, CitizenInstance ByRef citizenData, Boolean success)
   at HumanAI.PathfindFailure(UInt16 instanceID, CitizenInstance ByRef data)
   at TrafficManager.Custom.AI.CustomHumanAI.CustomSimulationStep(UInt16 instanceId, CitizenInstance ByRef instanceData, Vector3 physicsLodRefPos)
   at CitizenManager.SimulationStepImpl(Int32 subStep)
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at CitizenManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
```

```diff
- Simulation error: Array index is out of range.
  at TerrainManager.GetSurfaceCell (Int32 x, Int32 z) [0x00000] in <filename unknown>:0 
  at TerrainManager.SampleDetailSurface (Single x, Single z) [0x00000] in <filename unknown>:0 
  at TerrainManager.SampleDetailSurface (Vector3 worldPos) [0x00000] in <filename unknown>:0 
  at WildlifeAI.IsFreePosition (Vector3 position) [0x00000] in <filename unknown>:0 
  at WildlifeAI.SimulationStep (UInt16 instanceID, .CitizenInstance& citizenData, .Frame& frameData, Boolean lodPhysics) [0x00000] in <filename unknown>:0 
  at CitizenAI.SimulationStep (UInt16 instanceID, .CitizenInstance& data, Vector3 physicsLodRefPos) [0x00000] in <filename unknown>:0 
  at WildlifeAI.SimulationStep (UInt16 instanceID, .CitizenInstance& data, Vector3 physicsLodRefPos) [0x00000] in <filename unknown>:0 
  at CitizenManager.SimulationStepImpl (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManagerBase`2[Manager,Properties].SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at CitizenManager.ISimulationManager.SimulationStep (Int32 subStep) [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationStep () [0x00000] in <filename unknown>:0 
  at SimulationManager.SimulationThread () [0x00000] in <filename unknown>:0   [Core]
```

Mods that potentially integrate with TM:PE (and, if so, might need updates):

* **Parallel road tool** might need updating for v11 compatibility - tagging @ST-Apps
* **Roundabout builder** might need updating for v11 compatibility - tagging @Strdate
* **Smart intersections** might need updating for v11 compatibility - tagging @Strdate

**Comment by aubergine10** [comment]
```diff
- Simulation error: Array index is out of range.
+  at TerrainManager
```

Is likely [caused by clicking "Unlock all tiles" button in 81 Tiles mod](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/wiki/Array-Index---Symptom-11]

**Comment by aubergine10** [comment]
[Player.log](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/files/4174772/player.1.log)

**Comment by Strdate** [comment]
I don't think that any of these errors are caused by my mods.
It seems tahat with v11 setting priority signs from the roundabout builder no longer works

`((TrafficManager.UI.SubTools.PrioritySignsTool)TrafficManager.UI.UIBase.GetTrafficManagerTool().GetSubTool(TrafficManager.UI.ToolMode.AddPrioritySigns)).SetPrioritySign(m_segment.Id, m_startNode, TrafficManager.Traffic.Data.PrioritySegment.PriorityType.Yield);`

I wish that the backward compatibility could have been preserved

**Comment by aubergine10** [comment]
We will soon have an alternative way to do that perhaps with the stuff that @kianzarrin is working on.

**Comment by Strdate** [comment]
Well, and since then?
I found that the problem is that the namespace for this enum changed
`TrafficManager.Traffic.Data.PrioritySegment.PriorityType`
I cannot reference both old and new TMPE at the same time. Visual Studio complaints that the dlls must be signed to do that and I didn't find way to circumvent it. So I either need to choose one of the versions to support or employ some dirty hack (I am working on it for 2 hours already)
Or you can provide me with some bridge right now, for example a method
`SetPrioritySign(ushort param1, bool param2, int param3)` which uses integer type instead of an enum.

**Comment by aubergine10** [comment]
@kianzarrin any ideas?

**Comment by kvakvs** [comment]
There was a several months old ticket to provide an API for features like this.
As it never went forward, might be a good day to dig it out and make that function @Strdate is asking for, as a good start for external stable API.

**Comment by Strdate** [comment]
I don't think you can call a method via reflection with incorrect argument type. The required type is that kind of enum I can't reference thus I can't provide it as an argument to the Invoke method. If the argument was something I know at compile time (Integer), then I can call the method.
But anyway, I'm working on a hack to make it work as it is.

**Comment by aubergine10** [comment]
This is going to sound crazy and the approach is probably slow (not not critical as it will only be used on rarely happening user interactions), but could we set up something on the TM:PE button where other mods can send message to it? (I think either @kvakvs or @krzychu124 looked in to this previously).

External mod would find TM:PE button (if not found, then obviously no API) and use Unity's send message (or whatever it's called) to send a small packet of text data to TM:PE.

Rough idea of packet format (could be anything): `intent:type=id, ... ; intent: ...`

Where `intent` let's tmpe know what is being requested (eg. `roundabout`), type is some object type recognised by the intent (eg. `node` or `segment`) and `id` is the ID of that thing (eg. node id or segment id etc).

TMPE would then apply the relevant bulk applicator tool (or whatever).

One of the intents would be `debug:true` (or `false` to turn off) which could toggle extended debug logging of TM:PE intent parser.

In the case of roundabout, a list of segments or junctions would be provided - whatever is sufficient for the `roundabout` intent to know what to apply it's magic to.

If an API is not provided by a given version of TM:PE it just won't do anything, rather than failing. We can also vesion control intents, for example `roundabout-v1: ...` so that backwards compatibility has a good chance of being maintained.

The intents stuff would also tie in nicely with recent discussions in #600 (TMPE support in asset editor).

**Comment by kianzarrin** [comment]
@Strdate I have a code here that deals with different versions of NS2:
https://github.com/kianzarrin/HideTMPECrosswalks/blob/master/HideTMPECrosswalks/Utils/NS2Utils.cs

I also saw this code in CSUR toolbox which looks better:
```c#
                        Loader.Detours.Add(new Loader.Detour(Assembly.Load("TrafficManager").GetType("TrafficManager.UI.SubTools.LaneConnectorTool").GetMethod("CheckSegmentsTurningAngle", BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[] { typeof(ushort), typeof(NetSegment).MakeByRefType(), typeof(bool), typeof(ushort), typeof(NetSegment).MakeByRefType(), typeof(bool) }, null),
                                           typeof(NewLaneConnectorTool).GetMethod("CheckSegmentsTurningAngle", BindingFlags.NonPublic | BindingFlags.Instance, null, new Type[] { typeof(ushort), typeof(NetSegment).MakeByRefType(), typeof(bool), typeof(ushort), typeof(NetSegment).MakeByRefType(), typeof(bool) }, null)));
```
if the returned method info is null then you can check for alternate arguments i guess.

**Comment by Strdate** [comment]
I ended up doing this:
`var prioritySignsTool = (TrafficManager.UI.SubTools.PrioritySignsTool)TrafficManager.UI.UIBase.GetTrafficManagerTool().GetSubTool(TrafficManager.UI.ToolMode.AddPrioritySigns);
            var setPrioritySign = prioritySignsTool.GetType().GetMethod("SetPrioritySign",BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance);

            setPrioritySign.Invoke(prioritySignsTool, new object[] { m_segment.Id, m_startNode, 3 });`

As you can see, you can invoke methods that require enum parameters with integers! Thanks God!
By the way, for some reason the visibility of the SetPrioritySign method changed to private, so I couldn't invoke it normally even if I wanted to. Nice trap.

**Comment by kvakvs** [comment]
We try to reduce visibility where possible.
With reflection you still can see everything, even private. It's in `BindingFlags.*`

**Comment by Strdate** [comment]
Apparently this wasn't a good place to do it. But never mind, I needed to use the reflection anyway

**Comment by aubergine10** [comment]
@pallamf : 

* We'll continue diagnosing your 'game stuck on load' issue in #695 (3rd day update)

@kvakvs , @Strdate :

* (OP) has sent us new logs in #695 which contain no errors so it looks like the issues with 81 Tiles, and also Roundabout Buidler, are resolved.
* If continuation is required regarding TM:PE API please continue that in #685 or #672 or start new issue

@Strdate : 

* From v11.1.0 onwards, TM:PE version can be obtianed reliably from the Assembly version, for example:

```cs
Version TMPE_Version = Assembly.Load("TrafficManager").GetName().Version;
if (TMPE_Version >= new Version(11, 1, 1)) {
   // do something bsaed on TM:PE v1.1.1.* or above
}
```

All earlier releases, including 11.0 have assembly version `1.0.*.*`.
